version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8
    commands:
      - echo "Instalando ferramentas..."
      - dotnet tool install -g Amazon.Lambda.Tools || true
      - export PATH="$PATH:$HOME/.dotnet/tools"

  build:
    commands:
      - echo "Restaurando dependências..."
      - cd HelloLambda
      - dotnet restore
      - echo "Buildando projeto..."
      - dotnet build -c Release
      - echo "Gerando pacote Lambda..."
      - dotnet lambda package --configuration Release --framework net8.0 --output-package ../artifact/function.zip
      - cd ..

  post_build:
    commands:
      - echo "Atualizando Lambda e publicando nova versão"
      - VERSION=$(aws lambda update-function-code --function-name poc-hello-lambda --zip-file fileb://artifact/function.zip --query 'Version' --output text)
      - echo "Nova versão publicada: $VERSION"
      - aws lambda publish-version --function-name poc-hello-lambda
      - aws lambda update-alias --function-name poc-hello-lambda --name prod --function-version $VERSION

artifacts:
  files:
    - artifact/function.zip
    - appspec.yml