version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8
    commands:
      - echo "🚀 Instalando ferramentas..."
      - dotnet tool install -g Amazon.Lambda.Tools || true
      - export PATH="$PATH:$HOME/.dotnet/tools"

  pre_build:
    commands:
      - echo "🔄 Restaurando dependências..."
      - cd HelloLambda
      - dotnet restore

  build:
    commands:
      - echo "🏗️ Publicando aplicação..."
      - dotnet publish -c Release -f net8.0 -o ./publish

      - echo "📦 Criando pacote function.zip na raiz..."
      - cd publish
      - zip -r ../../../function.zip .

  post_build:
    commands:
      - echo "✅ Build concluído com sucesso."

artifacts:
  files:
    - function.zip
    - appspec.yml
